-- 011 — Ryanair e British Airways passam a saber buscar ida-e-volta
--
-- A 008 deixou `has_roundtrip` só na Azul porque só ela tinha o fluxo RT. As
-- duas agora têm, e cada uma de um jeito — o que importa aqui é que ambas
-- devolvem as duas pernas de UMA busca, que é o que a 008 exige:
--
--   ryanair        `isReturn=true&dateIn=…` traz os dois grids na mesma tela.
--                  Sem laço 1-para-N: medido em STN↔DUB e BGY↔BCN, o preço das
--                  voltas é idêntico antes e depois de escolher a ida, então as
--                  voltas vêm sem paired_outbound_flight e qualquer ida combina
--                  com qualquer volta.
--
--   britishairways `onds=A-B_ida,B-A_volta` com `ond=2`, com laço 1-para-N: a
--                  mesma volta mudou de R$8.724 para R$8.754 só por trocar a
--                  ida, então cada volta vem carimbada com a ida que a
--                  precificou. As duas pernas somam o total real (R$4.925 +
--                  R$8.724 = R$13.648,68 no resumo da reserva da própria BA),
--                  por isso não há bundle a registrar.
--
-- A LATAM segue em false: o fluxo RT dela não foi implementado porque o site
-- não respondeu a nenhuma busca durante a investigação — nem no one-way que já
-- existia (ver memory/latam/scraper-architecture.md na scraping.API).
--
-- Idempotente.

UPDATE airlines SET has_roundtrip = true WHERE code IN ('ryanair', 'britishairways');
